# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_th', '0010_userservice_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='duration',
            field=models.CharField(choices=[('d', 'Day'), ('w', 'Week'), ('m', 'Month'), ('n', 'None')], default='n',
                                   max_length=1),
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('link', models.URLField()),
                ('duration', models.CharField(max_length=1)),
                ('date_end', models.DateField()),
                ('provider', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
