# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_th', '0011_digest'),
        ('th_wallabag', '0002_auto_20171002_1426')
    ]

    operations = [
        migrations.CreateModel(
            name='Slack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('webhook_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('slack_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('team_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_th_slack',
            },
        ),
        migrations.CreateModel(
            name='Taiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=50)),
                ('webhook_secret_key', models.CharField(blank=True, max_length=50, unique=True)),
                ('notify_epic_create', models.BooleanField(default=True)),
                ('notify_epic_change', models.BooleanField(default=True)),
                ('notify_epic_delete', models.BooleanField(default=True)),
                ('notify_relateduserstory_create', models.BooleanField(default=True)),
                ('notify_relateduserstory_delete', models.BooleanField(default=True)),
                ('notify_issue_create', models.BooleanField(default=True)),
                ('notify_issue_change', models.BooleanField(default=True)),
                ('notify_issue_delete', models.BooleanField(default=True)),
                ('notify_userstory_create', models.BooleanField(default=True)),
                ('notify_userstory_change', models.BooleanField(default=True)),
                ('notify_userstory_delete', models.BooleanField(default=True)),
                ('notify_task_create', models.BooleanField(default=True)),
                ('notify_task_change', models.BooleanField(default=True)),
                ('notify_task_delete', models.BooleanField(default=True)),
                ('notify_wikipage_create', models.BooleanField(default=True)),
                ('notify_wikipage_change', models.BooleanField(default=True)),
                ('notify_wikipage_delete', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'django_th_taiga',
            },
        ),
        migrations.CreateModel(
            name='Wallabag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('tag', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'db_table': 'django_th_wallabag',
            },
        ),
        migrations.AddField(
            model_name='triggerservice',
            name='counter_ko',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='triggerservice',
            name='counter_ok',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userservice',
            name='counter_ko',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userservice',
            name='counter_ok',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rss',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='triggerservice',
            name='date_result',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='wallabag',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_th.TriggerService'),
        ),
        migrations.AddField(
            model_name='taiga',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_th.TriggerService'),
        ),
        migrations.AddField(
            model_name='slack',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_th.TriggerService'),
        ),
    ]
