# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_th', '0012_auto_20171003_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservice',
            name='host',
            field=models.URLField(blank=True, default='', verbose_name='host'),
        ),
    ]
